### ISSUE TITLE
Tidy up Project 22

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1878]
Original [Slack thread](https://bennettoxford.slack.com/archives/C31D62X5X/p1655302348888339)

@andrewscolm has picked up a new project.  @amirmehrkar has determined it fits under the remit of [Project 22](https://www.opensafely.org/approved-projects/#project-22) ([original application](https://docs.google.com/document/d/1P0j7gs3mEganao2DVO5arNC3ZGtT3jay2Yq40f4pQg0/edit#heading=h.ya05m3g3094i), [job-server application](https://jobs.opensafely.org/staff/applications/602c/)).  Project 22 predates moving applications to job-server so it's various components need a little tidying up.

There are two projects on job-server which need merging:
* https://jobs.opensafely.org/datalab/change-in-effectiveness-of-covid-19-vaccination-over-time-in-fully-vaccinated-individuals/ (this one predates Organisation support in job-server)
* https://jobs.opensafely.org/university-of-bristol/covid-vaccine-effectiveness/

**Tasks**
* [x] Talk to Elsie about merging the two projects to determine how to do it
* [x] Merge the two projects [probably], blocked by #1848 
* [x] Link the [latter project](https://jobs.opensafely.org/university-of-bristol/covid-vaccine-effectiveness/waning-ve-2dose-cancer/) to the [application](https://jobs.opensafely.org/staff/applications/602c/)
* [x] Set the number of the [latter project](https://jobs.opensafely.org/university-of-bristol/covid-vaccine-effectiveness/) to `22` in the Staff Area
* [x] Find out when Amir approved the application (`2021-11-03`)
* [x] Set `approved_at` to the date from Amir and `approved_by` to Amir via the Django shell

**Comment by ghickman** [comment]
This still needs the GDocs version comparing to the job-server one and ideally a quick way to lock the GDocs version.

**Comment by ghickman** [comment]
I can't see any changes in the GDoc so calling this one done.
