### ISSUE TITLE
Epic Restyle

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/job-server#2284]
## /

- [x] base.html
- [x] error.html
- [x] index-authenticated.html
- [x] index-unauthenticated.html
- [x] job_detail.html
- [x] job_request_create.html
- [x] job_request_detail.html
- [x] job_request_list.html
- [x] login.html
- [x] org_detail.html
- [x] org_event_log.html
- [x] org_list.html
- [x] outputs-spa.html
- [x] project_detail.html
- [x] project_edit.html
- [x] project_event_log.html
- [x] project_release_list.html
- [x] project_repo_list.html
- [x] project_report_list.html
- [x] release_detail.html
- [x] settings.html
- [x] sign_off_repo.html
- [x] snapshot_detail.html
- [x] status.html
- [x] user_detail.html
- [x] user_event_log.html
- [x] user_list.html
- [x] workspace_analysis_request_list.html
- [x] workspace_backend_files.html
- [x] workspace_create.html
- [x] workspace_create_error.html
- [x] workspace_detail.html
- [x] workspace_edit.html
- [x] workspace_event_log.html
- [x] workspace_file_list.html
- [x] workspace_latest_outputs_detail.html
- [x] workspace_output_list.html
- [x] workspace_release_list.html

## applications

- [x] application_list.html
- [x] apply.html
- [x] base.html
- [x] confirmation.html
- [x] page.html
- [x] page_researchers.html
- [x] researcher_form.html
- [x] sign_in.html
- [x] terms.html

## emails

- [x] base.html
- [x] base.txt
- [x] login.html
- [x] login.txt
- [x] login_token_generated.html
- [x] login_token_generated.txt
- [x] login_token_used.html
- [x] login_token_used.txt
- [x] login_via_github.html
- [x] login_via_github.txt
- [x] notify_finished.html
- [x] notify_finished.txt
- [x] notify_report_uploaded.html
- [x] notify_report_uploaded.txt
- [x] notify_researcher_repo_signed_off.html
- [x] notify_researcher_repo_signed_off.txt
- [x] notify_staff_repo_signed_off.html
- [x] notify_staff_repo_signed_off.txt
- [x] report_published.html
- [x] report_published.txt
- [x] reset_password.txt
- [x] welcome.html
- [x] welcome.txt

## interactive

- [x] analysis_request_create.html
- [x] analysis_request_detail.css
- [x] analysis_request_detail.html
- [x] publish_request_create.html
- [x] publish_request_create_locked.html
- [x] report_edit.html
- [x] report_edit_locked.html

## pipeline

- [x] require_name.html

## staff

- analysis_request
  - [x] detail.html
  - [x] list.html
- application
  - [x] approve.html
  - [x] detail.html
  - [x] edit.html
  - [x] list.html
  - [x] researcher_edit.html
- backend
  - [x] create.html
  - [x] detail.html
  - [x] edit.html
  - [x] list.html
- [x] base-tw.html
- dashboards
  - [x] copiloting.html
  - [x] index.html
  - [x] projects.html
  - [x] repos.html
  - [x] repos_with_multiple_projects.html
- [x] index.html
- job_request
  - [x] detail.html
  - [x] list.html
- org
  - [x] create.html
  - [x] create.htmx.html
  - [x] detail.html
  - [x] edit.html
  - [x] list.html
- project
  - [x] detail.html
  - [x] edit.html
  - [x] list.html
- [x] project_create.form.html
- [x] project_create.html
- [x] project_create.htmx.html
- [x] project_link_application.html
- [x] project_membership_create.html
- [x] project_membership_edit.html
- [x] publish_request_detail.html
- [x] publish_request_list.html
- redirect
  - [x] detail.html
  - [x] list.html
- repo
  - [x] detail.html
  - [x] list.html
- report
  - [x] detail.html
  - [x] list.html
- sentry
  - [x] index.html
  - [x] message.html
- user
  - [x] create.html
  - [x] detail_with_email.html
  - [x] detail_with_oauth.html
  - [x] list.html
  - [x] role_list.html
  - [x] set_orgs.html
- workspace
  - [x] detail.html
  - [x] edit.html
  - [x] list.html

## yours

- [x] analysis_request_list.html
- [x] org_list.html
- [x] project_list.html
- [x] workspace_list.html
