### ISSUE TITLE
Allow "any time" option for codelist 2 time period

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#2901]
Allow users to choose a time period of "any time" for the codelist 2 lookback period. Currently we allow a time period of up to [ten years](https://github.com/opensafely-core/job-server/issues/2876), but for some codelists, particularly those for long term conditions, we may not want to restrict it. This would also pick up any events with spurious dates (e.g 1900-01-01).

This will involve changing the form, the data we're passing to the interactive-template renderer and the analysis code.

The analysis code will require an extra variable to be passed in. Louis to update this and then speak to George to update the django side.

![Image](https://user-images.githubusercontent.com/3889554/228848553-7a061428-aa0d-4116-bf5c-ce7b514a7d46.png)

## PRs

- [x] [Research template changes (opensafely-core/interactive-templates#88)](https://github.com/opensafely-core/interactive-templates/pull/88)
- [x] [Django changes (opensafely-core/job-server#2956)](https://github.com/opensafely-core/job-server/pull/2956)
- [x] [Front-end changes (opensafely-core/job-server#2992)](https://github.com/opensafely-core/job-server/pull/2992)

**Comment by LFISHER7** [comment]
https://github.com/opensafely-core/interactive-templates/pull/88 updates the analysis code to support this

**Comment by ghickman** [comment]
Django and analysis template parts of this are done.

@tomodwyer – Django is expecting a `time_ever` key in the posted data, you should be able to leave it empty for unchecked and any string value for checked since it normalises to true/false on the python side.

**Comment by tomodwyer** [comment]
@ghickman to confirm, the data from the front-end will provide the following JSON. Is this what Django is expecting?

## If "any time" is selected

```json
{
    "codelistA": {
        "label": "Aplastic Anaemia (SNOMED)",
        "type": "event",
        "value": "opensafely/aplastic-anaemia-snomed/2020-04-24"
    },
    "codelistB": {
        "label": "Aplastic Anaemia (SNOMED)",
        "type": "event",
        "value": "opensafely/aplastic-anaemia-snomed/2020-04-24"
    },
    "startDate": "2019-09-01",
    "endDate": "2023-03-31",
    "timeEver": "true",
    "filterPopulation": "adults",
    "demographics": [
        "age",
        "ethnicity"
    ],
    "title": "asdasdsad",
    "purpose": "asdasdasda"
}
```

## If a time value (for example, 5 years) is selected

```json
{
    "codelistA": {
        "label": "Aplastic Anaemia (SNOMED)",
        "type": "event",
        "value": "opensafely/aplastic-anaemia-snomed/2020-04-24"
    },
    "codelistB": {
        "label": "Aplastic Anaemia (SNOMED)",
        "type": "event",
        "value": "opensafely/aplastic-anaemia-snomed/2020-04-24"
    },
    "startDate": "2019-09-01",
    "endDate": "2023-03-31",
    "timeEver": null,
    "timeScale": "years",
    "timeValue": 5,
    "filterPopulation": "adults",
    "demographics": [
        "age",
        "ethnicity"
    ],
    "title": "asdasdsad",
    "purpose": "asdasdasda"
}
```

**Comment by tomodwyer** [comment]
Front-end added
