### ISSUE TITLE
Provide Output Checkers with the permission to view released files

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4518]
Output Checkers need the permission to view released files to be able to review what outputs have been previously released in order to assess whether it's appropriate to release further outputs. At the moment, they are given the global ProjectCollaborator role in addition to the OutputChecker role in order to give them the necessary permissions. However, we can solve this by providing the OutputChecker role with the that permission.

The problem was discussed in today's roles and permissions workshop and has also come up a few times in the past (https://github.com/opensafely-core/job-server/issues/1547, https://github.com/ebmdatalab/team-manual/issues/694).

## Acceptance criteria

- [x] Add the `release_file_view` permission to the OutputChecker role.
- [x] Update the output checking [documentation](https://github.com/ebmdatalab/team-manual/blob/a6e1fa1d1706996893e5598a577cf0840088d131/docs/products/output-checking.md?plain=1#L155)
- [x] Communicate the change with the output checking team
- [x] Write an ADR explaining the change to the OutputChecker role.

**Comment by Jongmassey** [comment]
[Add the release_file_view permission to the OutputChecker role. + Write an ADR explaining the change to the OutputChecker role.](https://github.com/opensafely-core/job-server/pull/4538)

[Update the output checking documentation](https://github.com/ebmdatalab/team-manual/pull/822)
