### ISSUE TITLE
Provide Project Developers with the permission to view released files

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-server#4519]
Researchers need the permission to view released files to be able to review the outputs that they've generated themselves. At the moment, they are given the global ProjectCollaborator role in addition to the ProjectDeveloper role in order to give them the necessary permissions. However, we can solve this by providing the ProjectDeveloper role with the that permission.

The problem was discussed in today's roles and permissions workshop and has also come up in the past (https://github.com/opensafely-core/job-server/issues/1547).

Complete #4520 before adding the extra permission to this role.

## Acceptance criteria

- [ ] Check with the IG team whether any of their documentation needs to be updated
- [ ] Add the `release_file_view` permission to the ProjectDeveloper role
- [ ] Communicate the change with the IG Team
- [ ] Write an ADR explaining the change to the ProjectDeveloper role.

**Comment by lucyb** [comment]
We're keeping this work on hold for one week, until we know the outcome of our next permissions meeting on Thursday. It's likely that we will change this role anyway, so we may decide there's no need to do this work. Although, if it looks unlikely that we'll change anything for a while, this will be a good short term solution.

**Comment by mikerkelly** [comment]
Discussed this ticket with Lucy. While Jon is right that this this is technically straightforward, agreeing the requirements with eg IG and ensuring that the change is properly documented and reflected in policy and practice is more complicated. So I’ve unassigned it from me and removed the “good first issue” label. Hope that makes sense.

**Comment by Jongmassey** [comment]
[IG Team thread](https://bennettoxford.slack.com/archives/C04NHSU5DRB/p1727289079537279)

Linked [Job Server](https://github.com/opensafely-core/job-server/pull/4626) and [Team Manual](https://github.com/ebmdatalab/team-manual/pull/885) PRs can be merged once IG give 👍

**Comment by Jongmassey** [comment]
do we want to add a data migration to remove assignments of `ProjectCollaborator` from users who also are assigned `ProjectDeveloper` ?

**Comment by lucyb** [comment]
I raised this in the NOD meeting this morning, where it was agreed that the decision to make this change could be made by Team REX. So, this ticket is no longer blocked.

We should let NOD and IG know once it's done, not least because Liam and Juliet will need to update their processes. 

Please don't do a data migration as part of this ticket. We can always return to it, if IG decide it's necessary.

**Comment by mikerkelly** [comment]
I've approved and merged both PRs and will notify IG/NOD in Slack.
